name: fly-deploy-backend-manual

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: GitHub Action for flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master
        with:
          version: "latest"

      - name: Deploy to Fly.io
        working-directory: backend
        run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
